package geminisdk;

public class Svs5ErrorType {

	public static final int SVS5_SEQUENCER_STATUS_OK               = 0;
	public static final int SVS5_SEQUENCER_ALREADY_STARTED         = ( SVS5_SEQUENCER_STATUS_OK | 1 );
	public static final int SVS5_SEQUENCER_NOT_RUNNING             = ( SVS5_SEQUENCER_STATUS_OK | 2 );
	public static final int SVS5_SEQUENCER_ANOTHER_INSTANCE_RUNNING= ( SVS5_SEQUENCER_STATUS_OK | 3 );
	public static final int SVS5_SEQUENCER_INVALID_CONFIG          = ( SVS5_SEQUENCER_STATUS_OK | 4 );
	public static final int SVS5_SEQUENCER_INVALID_PARAMETERS_SIZE = ( SVS5_SEQUENCER_STATUS_OK | 5 );
	public static final int SVS5_SEQUENCER_INVALID_PARAMETERS_VALUE= ( SVS5_SEQUENCER_STATUS_OK | 6 );
	public static final int SVS5_SEQUENCER_INVALID_PROPERTY_ID     = ( SVS5_SEQUENCER_STATUS_OK | 7 );
	public static final int SVS5_SEQUENCER_INVALID_PLAYBACK_FILE   = ( SVS5_SEQUENCER_STATUS_OK | 8 );
	
	public static String getErrorName(int errorCode) {
		switch (errorCode) {
		case SVS5_SEQUENCER_STATUS_OK:
			return "SVS5_SEQUENCER_STATUS_OK";
		case SVS5_SEQUENCER_ALREADY_STARTED:
			return "SVS5_SEQUENCER_ALREADY_STARTED";
		case SVS5_SEQUENCER_NOT_RUNNING:
			return "SVS5_SEQUENCER_NOT_RUNNING";
		case SVS5_SEQUENCER_ANOTHER_INSTANCE_RUNNING:
			return "SVS5_SEQUENCER_ANOTHER_INSTANCE_RUNNING";
		case SVS5_SEQUENCER_INVALID_CONFIG:
			return "SVS5_SEQUENCER_INVALID_CONFIG";
		case SVS5_SEQUENCER_INVALID_PARAMETERS_SIZE:
			return "SVS5_SEQUENCER_INVALID_PARAMETERS_SIZE";
		case SVS5_SEQUENCER_INVALID_PARAMETERS_VALUE:
			return "SVS5_SEQUENCER_INVALID_PARAMETERS_VALUE";
		case SVS5_SEQUENCER_INVALID_PROPERTY_ID:
			return "SVS5_SEQUENCER_INVALID_PROPERTY_ID";
		case SVS5_SEQUENCER_INVALID_PLAYBACK_FILE:
			return "SVS5_SEQUENCER_INVALID_PLAYBACK_FILE";
		}
		
		return "Unknown error code: " + errorCode;
	}

}
